sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

install:
  # Get boost
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost

script:
  - mkdir build && cd build
  - cmake ../ -DBUILD_SPICE="ON" -DBUILD_PYKEP="ON" -DBUILD_MAIN="ON" -DBUILD_TESTS="ON" -DPYTHON_MODULES_DIR="~/local/lib/python/site-packages" -DCMAKE_INSTALL_PREFIX="~/local"
  - make -j4
  - make test
  - make install

after_success:
  - export PYTHONPATH=~/local/lib/python/site-packages
  - export LD_LIBRARY_PATH="~/local/lib;${BOOST_ROOT}/lib"
  - python -c "import PyKEP; print(PyKEP.__version__); print(PyKEP.__extensions__)"

branches:
  only:
    - test

notifications:
  email: false
